### ISSUE TITLE
生产环境下 ios注册信鸽 取不到Token测试过吗？

### ISSUE THREAD

**Issue by david-woody** [osvlabs/cordova-plugin-xgpush#1]
目前也在接入信鸽插件，开发环境下使用正常，但是生产环境下 死活注册不上，取不到token
也做了以下尝试
1、新建ios项目 原生接入 信鸽sdk 开发环境正常 生产环境正常   （说明证书没有问题）
2、新建 cordova项目 原生接入 信鸽sdk 开发环境正常 生产环境注册失败
你们在开发过程中有碰到类似的情况吗？

**Comment by Attiv** [comment]
抱歉才看到 issue
我们开发的时候 开发环境和生产环境是都可以收到的,获取 token应该跟环境无关吧,可以在 cordova 应用里使用 vconsole 或者 eruda 打印token或者存到 localStorage里面查看一下

**Comment by david-woody** [comment]
插件没有问题，尝试下了发现是cordova对ios生产环境的打包的兼容性问题，框架自动生成的文件 在加入通知授权的时候，正式环境添加不进去

**Comment by Attiv** [comment]
可以换换cordova的iOS版本，试试有没有 --release命令
可以build之后用用xcode打包发布 adhoc测试下
