### ISSUE TITLE
可以暂时先不开启厂商推送嘛？目前在安装的时候会报错

### ISSUE THREAD

**Issue by zaleGZL** [osvlabs/cordova-plugin-xgpush#2]
![image](https://user-images.githubusercontent.com/20339327/73590926-4d396380-4523-11ea-8844-cac4092c482a.png)
把其它的暂时设置成空字符串是否会影响使用呢？ @Joker-1991 @zhanghuanchong @django-wong

**Comment by Attiv** [comment]
可以试试
或者随便填
